[package]
name = "rust_test"
version = "0.1.0"
authors = ["Leif Wesche <wesche@usc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
dirs = "3.0"
rocket_cors = "0.5.1"
